"""Addressed parameter memory graph utilities."""

from apm.memory.addressing import (
    AddressedEvaluation,
    address_confusion_matrix,
    best_parent_by_observed_energy,
    evaluate_addressed_on_arrays,
    evaluate_addressed_on_task,
    evaluate_node_on_arrays,
    evaluate_node_on_task,
    observed_energy_matrix,
    select_addresses,
)
from apm.memory.dense import (
    DenseParameterMemory,
    EdgeMemoryStats,
    add_dense_delta,
    dense_edge_memory_stats,
    dense_graph_memory_bytes,
    dense_node_memory_bytes,
    dense_task_node_ids,
    effective_dense_params,
    init_dense_parameter_memory,
    tree_l2_norm,
    tree_nbytes,
    tree_parameter_count,
    tree_subtract,
)
from apm.memory.graph import (
    MemoryGraph,
    MemoryNode,
    NodeId,
    TaskId,
    add_memory_node,
    child_memory_nodes,
    init_memory_graph,
    memory_edge_node_ids,
    memory_node_by_id,
    memory_node_ids,
    memory_node_path,
    path_incidence_matrix,
)
from apm.memory.visualization import EdgeVisualStats, NodeVisualStats, write_memory_graph_svg

__all__ = [
    "AddressedEvaluation",
    "DenseParameterMemory",
    "EdgeMemoryStats",
    "EdgeVisualStats",
    "NodeVisualStats",
    "MemoryGraph",
    "MemoryNode",
    "NodeId",
    "TaskId",
    "add_dense_delta",
    "add_memory_node",
    "address_confusion_matrix",
    "best_parent_by_observed_energy",
    "child_memory_nodes",
    "dense_edge_memory_stats",
    "dense_graph_memory_bytes",
    "dense_node_memory_bytes",
    "dense_task_node_ids",
    "effective_dense_params",
    "evaluate_addressed_on_arrays",
    "evaluate_addressed_on_task",
    "evaluate_node_on_arrays",
    "evaluate_node_on_task",
    "init_dense_parameter_memory",
    "init_memory_graph",
    "memory_edge_node_ids",
    "memory_node_by_id",
    "memory_node_ids",
    "memory_node_path",
    "observed_energy_matrix",
    "path_incidence_matrix",
    "select_addresses",
    "tree_l2_norm",
    "tree_nbytes",
    "tree_parameter_count",
    "tree_subtract",
    "write_memory_graph_svg",
]
